<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 6 Advancing Statistics in R | A Guide to Getting Started with R</title>
<meta name="author" content="Pete Apicella">
<meta name="generator" content="bookdown 0.27 with bs4_book()">
<meta property="og:title" content="Chapter 6 Advancing Statistics in R | A Guide to Getting Started with R">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 6 Advancing Statistics in R | A Guide to Getting Started with R">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="style.css">
<meta name="description" content='install.packages("ggplot2", repos = "https://cran.us.r-project.org") install.packages("dplyr", repos = "https://cran.us.r-project.org") install.packages("ggfortify", repos =...'>
<meta property="og:description" content='install.packages("ggplot2", repos = "https://cran.us.r-project.org") install.packages("dplyr", repos = "https://cran.us.r-project.org") install.packages("ggfortify", repos =...'>
<meta name="twitter:description" content='install.packages("ggplot2", repos = "https://cran.us.r-project.org") install.packages("dplyr", repos = "https://cran.us.r-project.org") install.packages("ggfortify", repos =...'>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">A Guide to Getting Started with R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">About</a></li>
<li><a class="" href="getting-acqainted-with-r.html"><span class="header-section-number">1</span> Getting Acqainted with R</a></li>
<li><a class="" href="getting-data-into-r.html"><span class="header-section-number">2</span> Getting Data into R</a></li>
<li><a class="" href="data-management-and-manipulation.html"><span class="header-section-number">3</span> Data Management and Manipulation</a></li>
<li><a class="" href="visualizing-your-data.html"><span class="header-section-number">4</span> Visualizing your data</a></li>
<li><a class="" href="introduction-to-statistics-in-r.html"><span class="header-section-number">5</span> Introduction to Statistics in R</a></li>
<li><a class="active" href="advancing-statistics-in-r.html"><span class="header-section-number">6</span> Advancing Statistics in R</a></li>
<li><a class="" href="getting-started-with-generalized-linear-models.html"><span class="header-section-number">7</span> Getting Started with Generalized Linear Models</a></li>
<li><a class="" href="chapter-8-pimping-your-plots.html"><span class="header-section-number">8</span> Chapter 8: Pimping Your Plots</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/rstudio/bookdown-demo">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="advancing-statistics-in-r" class="section level1" number="6">
<h1>
<span class="header-section-number">6</span> Advancing Statistics in R<a class="anchor" aria-label="anchor" href="#advancing-statistics-in-r"><i class="fas fa-link"></i></a>
</h1>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"ggplot2"</span>,  repos <span class="op">=</span> <span class="st">"https://cran.us.r-project.org"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"dplyr"</span>,  repos <span class="op">=</span> <span class="st">"https://cran.us.r-project.org"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"ggfortify"</span>,  repos <span class="op">=</span> <span class="st">"https://cran.us.r-project.org"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sinhrks/ggfortify">ggfortify</a></span><span class="op">)</span></code></pre></div>
<div id="the-two-way-anova" class="section level2" number="6.1">
<h2>
<span class="header-section-number">6.1</span> The two-way ANOVA<a class="anchor" aria-label="anchor" href="#the-two-way-anova"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>the two-way ANOVA differs from the one-way version in that it involves two categorical/explanatory variables</li>
<li>the response variable in the two-way ANOVA may vary with both explanatory variables
<ul>
<li>if the way it varies depends on the other explanatory variable, then this phenomenon is known as a statistical interaction</li>
</ul>
</li>
</ul>
<p>Read in data:</p>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urlfile06a</span><span class="op">=</span><span class="st">"https://raw.githubusercontent.com/apicellap/data/main/growth.csv"</span>
<span class="va">growth.moo</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="va">urlfile06a</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://dplyr.tidyverse.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 48
## Columns: 3
## $ supplement &lt;chr&gt; "supergain", "supergain", "supergain", "supergain", "contro…
## $ diet       &lt;chr&gt; "wheat", "wheat", "wheat", "wheat", "wheat", "wheat", "whea…
## $ gain       &lt;dbl&gt; 17.37125, 16.81489, 18.08184, 15.78175, 17.70656, 18.22717,…</code></pre>
<div id="cow-growth-data" class="section level3" number="6.1.1">
<h3>
<span class="header-section-number">6.1.1</span> Cow Growth data<a class="anchor" aria-label="anchor" href="#cow-growth-data"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>this dataset deals with cows on different diets
<ul>
<li>cows were fed one of three diets:
<ul>
<li>wheat, oats, or barley</li>
</ul>
</li>
<li>each diet was then enhanced with one of four supplements:
<ul>
<li>supergrain, control, supersupp, agrimore</li>
</ul>
</li>
<li>each diet combination had 3 biological replicates (cows)</li>
</ul>
</li>
</ul>
<p>Coerce two of the variables into factors:</p>
<div class="sourceCode" id="cb148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">growth.moo</span><span class="op">$</span><span class="va">supplement</span> <span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">$</span><span class="va">supplement</span><span class="op">)</span> 
<span class="va">growth.moo</span><span class="op">$</span><span class="va">diet</span> <span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">$</span><span class="va">diet</span><span class="op">)</span> </code></pre></div>
<div class="sourceCode" id="cb149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">$</span><span class="va">diet</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "barley" "oats"   "wheat"</code></pre>
<div class="sourceCode" id="cb151"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">$</span><span class="va">supplement</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "agrimore"  "control"   "supergain" "supersupp"</code></pre>
<ul>
<li>in both of the previous code chunks the output is in alphabetical order</li>
<li>R always declares the first level alphabetically the reference level</li>
<li>in the case of the supplement variable, control must be made the reference level
<ul>
<li>this can be accomplished using the <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> function:</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb153"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">growth.moo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">growth.moo</span>,
                     supplement <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">supplement</span>, ref <span class="op">=</span> <span class="st">"control"</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">growth.moo</span><span class="op">$</span><span class="va">supplement</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "control"   "agrimore"  "supergain" "supersupp"</code></pre>
<p>Create summary dataframe:</p>
<div class="sourceCode" id="cb155"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sumMoo</span> <span class="op">&lt;-</span> <span class="va">growth.moo</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">diet</span>,<span class="va">supplement</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>meanGrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">gain</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'diet'. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb157"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sumMoo</span></code></pre></div>
<pre><code>## # A tibble: 12 × 3
## # Groups:   diet [3]
##    diet   supplement meanGrow
##    &lt;fct&gt;  &lt;fct&gt;         &lt;dbl&gt;
##  1 barley control        23.3
##  2 barley agrimore       26.3
##  3 barley supergain      22.5
##  4 barley supersupp      25.6
##  5 oats   control        20.5
##  6 oats   agrimore       23.3
##  7 oats   supergain      19.7
##  8 oats   supersupp      21.9
##  9 wheat  control        17.4
## 10 wheat  agrimore       19.6
## 11 wheat  supergain      17.0
## 12 wheat  supersupp      19.7</code></pre>
<div class="sourceCode" id="cb159"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sumMoo</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">supplement</span>, y<span class="op">=</span><span class="va">meanGrow</span>,
                   colour <span class="op">=</span> <span class="va">diet</span>,   <span class="co">#adds color by group</span>
                   group <span class="op">=</span> <span class="va">diet</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co">#</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="co">#connects the dots in each dataset </span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/cows-data-viz-06-1.png" width="672"></div>
<ul>
<li><p>the different supplements might have growth stimulating effects</p></li>
<li><p>the barley and/or oats diets might be better in stimulating growth relative to the wheat diet</p></li>
<li><p>since the lines are about parallel with each other, then we can probably rule out interaction effects. This means the effect of supplement probably does not depend on the effect of diet</p></li>
<li><p>but there might be an additive effect</p></li>
<li><p>null hypothesis: the effect of supplement type does not depend on diet</p></li>
</ul>
<p>Create a model to evaluate the null hypothesis:</p>
<div class="sourceCode" id="cb160"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">model_cow</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">gain</span> <span class="op">~</span> <span class="va">diet</span> <span class="op">*</span> <span class="va">supplement</span>, 
                data<span class="op">=</span><span class="va">growth.moo</span><span class="op">)</span>
<span class="va">model_cow</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gain ~ diet * supplement, data = growth.moo)
## 
## Coefficients:
##                   (Intercept)                       dietoats  
##                    23.2966499                     -2.8029851  
##                     dietwheat             supplementagrimore  
##                    -5.8911317                      3.0518277  
##           supplementsupergain            supplementsupersupp  
##                    -0.8305263                      2.2786527  
##   dietoats:supplementagrimore   dietwheat:supplementagrimore  
##                    -0.2471088                     -0.8182729  
##  dietoats:supplementsupergain  dietwheat:supplementsupergain  
##                    -0.0001351                      0.4374395  
##  dietoats:supplementsupersupp  dietwheat:supplementsupersupp  
##                    -0.9120830                     -0.0158299</code></pre>
<ul>
<li>function asks if the growth depends on diet, supplement, or an interaction between diet:supplement</li>
</ul>
<p>Check assumptions:</p>
<div class="sourceCode" id="cb162"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">model_cow</span>, smooth.colour <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/cows-assumptions-06-1.png" width="672"></div>
<ul>
<li>plot output: they look okay, but not ideal
<ul>
<li>top left - no pattern that would suggest model is inappropriate</li>
<li>top right - less than ideal because the positive and negative residuals are smaller than expected but the general linear model will be able to deal with these deviations from normality</li>
<li>bottom left - looks fine, virtually no pattern</li>
<li>bottom right - no serious outliers, looks fine</li>
</ul>
</li>
</ul>
<p>Create ANOVA table:</p>
<div class="sourceCode" id="cb163"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">model_cow</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: gain
##                 Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## diet             2 287.171 143.586 83.5201 2.999e-14 ***
## supplement       3  91.881  30.627 17.8150 2.952e-07 ***
## diet:supplement  6   3.406   0.568  0.3302    0.9166    
## Residuals       36  61.890   1.719                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>the diet:supplement row shows a small F value and a p value of 0.91 (way bigger than 0.05)</li>
<li>there is no statistically significant effect contributed by the two variables together</li>
<li>revisit the importance of a big F value</li>
</ul>
<p>Create summary table:</p>
<div class="sourceCode" id="cb165"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model_cow</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gain ~ diet * supplement, data = growth.moo)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.48756 -1.00368 -0.07452  1.03496  2.68069 
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   23.2966499  0.6555863  35.536  &lt; 2e-16 ***
## dietoats                      -2.8029851  0.9271390  -3.023  0.00459 ** 
## dietwheat                     -5.8911317  0.9271390  -6.354 2.34e-07 ***
## supplementagrimore             3.0518277  0.9271390   3.292  0.00224 ** 
## supplementsupergain           -0.8305263  0.9271390  -0.896  0.37631    
## supplementsupersupp            2.2786527  0.9271390   2.458  0.01893 *  
## dietoats:supplementagrimore   -0.2471088  1.3111726  -0.188  0.85157    
## dietwheat:supplementagrimore  -0.8182729  1.3111726  -0.624  0.53651    
## dietoats:supplementsupergain  -0.0001351  1.3111726   0.000  0.99992    
## dietwheat:supplementsupergain  0.4374395  1.3111726   0.334  0.74060    
## dietoats:supplementsupersupp  -0.9120830  1.3111726  -0.696  0.49113    
## dietwheat:supplementsupersupp -0.0158299  1.3111726  -0.012  0.99043    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.311 on 36 degrees of freedom
## Multiple R-squared:  0.8607, Adjusted R-squared:  0.8182 
## F-statistic: 20.22 on 11 and 36 DF,  p-value: 3.295e-12</code></pre>
<ul>
<li>output:
<ul>
<li>the intercept is the reference point for the table. it’s the barley-control because barley is alphabetically first</li>
<li>and we already set the reference to be the control</li>
<li>the Estimate column is the difference between the reference level and the level in each row</li>
</ul>
</li>
</ul>
<p>Generate new summary table:</p>
<div class="sourceCode" id="cb167"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sumMoo</span> <span class="op">&lt;-</span> <span class="va">growth.moo</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">diet</span>,<span class="va">supplement</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>meanGrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">gain</span><span class="op">)</span>,
            seGrow <span class="op">=</span> 
              <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">gain</span><span class="op">)</span><span class="op">/</span>
              <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span>
                <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>  <span class="co">#n() counts the number of observations in each group </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'diet'. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb169"><pre class="downlit sourceCode r">
<code class="sourceCode R">                      <span class="co">#side note: n() will count observations even if they have missing values</span>
  <span class="va">sumMoo</span>        </code></pre></div>
<pre><code>## # A tibble: 12 × 4
## # Groups:   diet [3]
##    diet   supplement meanGrow seGrow
##    &lt;fct&gt;  &lt;fct&gt;         &lt;dbl&gt;  &lt;dbl&gt;
##  1 barley control        23.3  0.703
##  2 barley agrimore       26.3  0.919
##  3 barley supergain      22.5  0.771
##  4 barley supersupp      25.6  1.06 
##  5 oats   control        20.5  0.506
##  6 oats   agrimore       23.3  0.613
##  7 oats   supergain      19.7  0.349
##  8 oats   supersupp      21.9  0.413
##  9 wheat  control        17.4  0.460
## 10 wheat  agrimore       19.6  0.710
## 11 wheat  supergain      17.0  0.485
## 12 wheat  supersupp      19.7  0.475</code></pre>
<p>Replot the data with standard error bars:</p>
<div class="sourceCode" id="cb171"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sumMoo</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">supplement</span>, y<span class="op">=</span><span class="va">meanGrow</span>,
                   colour <span class="op">=</span> <span class="va">diet</span>,   <span class="co">#adds color by group</span>
                   group <span class="op">=</span> <span class="va">diet</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co">#</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="co">#connects the dots in each dataset </span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">meanGrow</span> <span class="op">-</span> <span class="va">seGrow</span>,
                    ymax <span class="op">=</span> <span class="va">meanGrow</span> <span class="op">+</span> <span class="va">seGrow</span><span class="op">)</span>, width <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/cows-data-viz2-1.png" width="672"></div>
</div>
</div>
<div id="analysis-of-covariance-ancova" class="section level2" number="6.2">
<h2>
<span class="header-section-number">6.2</span> Analysis of Covariance (ANCOVA)<a class="anchor" aria-label="anchor" href="#analysis-of-covariance-ancova"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>this linear model is unique in that it combines a categorical explanatory variable with a continuous explanatory variable</li>
</ul>
<p>Read in data:</p>
<div class="sourceCode" id="cb172"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">urlfile06b</span><span class="op">=</span><span class="st">"https://raw.githubusercontent.com/apicellap/data/main/limpet.csv"</span>
<span class="va">limp</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="va">urlfile06b</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://dplyr.tidyverse.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">limp</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 24
## Columns: 3
## $ DENSITY &lt;int&gt; 8, 8, 8, 8, 8, 8, 15, 15, 15, 15, 15, 15, 30, 30, 30, 30, 30, …
## $ SEASON  &lt;chr&gt; "spring", "spring", "spring", "summer", "summer", "summer", "s…
## $ EGGS    &lt;dbl&gt; 2.875, 2.625, 1.750, 2.125, 1.500, 1.875, 2.600, 1.866, 2.066,…</code></pre>
<ul>
<li>this dataset involves egg production by limpets
<ul>
<li>there are 4 density conditions in two production seasons</li>
</ul>
</li>
<li>the response (y) variable is egg production</li>
<li>the independent (x) variables include:
<ul>
<li>density (continuous)</li>
<li>season (categorical)</li>
</ul>
</li>
<li>this is a study of density dependent reproduction</li>
<li>Does density dependence of egg production differ between the spring and summer seasons?</li>
</ul>
<p>Coerce variable into a factor:</p>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">limp</span><span class="op">$</span><span class="va">SEASON</span> <span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">limp</span><span class="op">$</span><span class="va">SEASON</span><span class="op">)</span> 
<span class="fu"><a href="https://rdrr.io/r/base/factor.html">is.factor</a></span><span class="op">(</span><span class="va">limp</span><span class="op">$</span><span class="va">SEASON</span><span class="op">)</span> <span class="co">#allows you to check that the coercion worked </span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Start by plotting the data:</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">limp</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">DENSITY</span>, y <span class="op">=</span> <span class="va">EGGS</span>, colour<span class="op">=</span><span class="va">SEASON</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co">#colour - gives color to the two levels of the categorical variable, Grazing</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>spring <span class="op">=</span> <span class="st">"green"</span>, summer <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Limpet Density"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Eggs produced"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span>  </code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/limp-plot-1.png" width="672"></div>
<ul>
<li>Output observations:
<ul>
<li>As limpet density increases, there seems to be a decrease in egg production</li>
<li>There appears to be a seasonal difference in egg production in which yields are better in spring than in summer
<ul>
<li>mathematically, the intercept (the value of egg production) at a density of 0 is higher in spring</li>
</ul>
</li>
</ul>
</li>
<li>Thinking about this plot in terms of regression:
<ul>
<li>y is egg production</li>
<li>x is density</li>
<li>b is where the line crosses the y axis (egg production when density = 0)</li>
<li>m is the slope of the egg production density relationship -</li>
<li>Change in egg production per unit change in density - strength of density dependence</li>
</ul>
</li>
</ul>
<div class="inline-figure">Verbal, mathematical, R, and graphical interpretations of various hypotheses related to the ANCOVA that translate into specific linear models:
<img src="gswrtable.png" width="90%">
</div>
<ul>
<li>In the above table, neither A or B reflect the data in the limpet density scatterplot</li>
<li>E also does not do the data justice because the slopes are approximately parallel</li>
<li>C and D are possible
<ul>
<li>D is the best explanation of the data</li>
</ul>
</li>
<li>The difference between E and D is the presence (E) or absence (D) of an interaction term that specifies that the slopes are different
<ul>
<li>An interaction would look like - “The effect on density on egg production depends on the season”
<ul>
<li>The effect of density on egg production = slope value</li>
<li>Depends on the season = values may differ depending on the season</li>
</ul>
</li>
</ul>
</li>
</ul>
<div id="constructing-the-ancova" class="section level3" number="6.2.1">
<h3>
<span class="header-section-number">6.2.1</span> Constructing the ANCOVA<a class="anchor" aria-label="anchor" href="#constructing-the-ancova"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">limp.mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">EGGS</span> <span class="op">~</span> <span class="va">DENSITY</span> <span class="op">*</span> <span class="va">SEASON</span>, <span class="co">#expression says we want model to analyze a (main) effect of DENSITY,</span>
               <span class="co">#a (main) effect of SEASON, and the potential for the effect of DENSITY</span>
               <span class="co">#to depend on SEASON (interaction )</span>
               
               data <span class="op">=</span> <span class="va">limp</span><span class="op">)</span>

<span class="va">limp.mod</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EGGS ~ DENSITY * SEASON, data = limp)
## 
## Coefficients:
##          (Intercept)               DENSITY          SEASONsummer  
##             2.664166             -0.033650             -0.812282  
## DENSITY:SEASONsummer  
##             0.003114</code></pre>
<ul>
<li>Null hypothesis: the interaction term is not significant
<ul>
<li>That is to say - there are no differences in the slopes for each season
<ul>
<li>There is no extra variation explained by fitting different slopes</li>
</ul>
</li>
</ul>
</li>
</ul>
<p>Fetch the coefficients (intercepts and slope estimates), the residuals, the fitted values, etc.:</p>
<div class="sourceCode" id="cb179"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">limp.mod</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "coefficients"  "residuals"     "effects"       "rank"         
##  [5] "fitted.values" "assign"        "qr"            "df.residual"  
##  [9] "contrasts"     "xlevels"       "call"          "terms"        
## [13] "model"</code></pre>
<p>Check assumptions:</p>
<div class="sourceCode" id="cb181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">limp.mod</span>,smooth.colour <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/limp-assumptions-1.png" width="672"></div>
<ul>
<li>The assumptions are met according to the above figures</li>
</ul>
<p>Generate an anova table:</p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">limp.mod</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: EGGS
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## DENSITY         1 5.0241  5.0241 30.1971 2.226e-05 ***
## SEASON          1 3.2502  3.2502 19.5350 0.0002637 ***
## DENSITY:SEASON  1 0.0118  0.0118  0.0711 0.7925333    
## Residuals      20 3.3275  0.1664                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>output:
<ul>
<li>big F values/small p values - DENSITY and SEASON - effects are significant/unlikely to be the result of chance
<ul>
<li>effects of DENSITY and SEASON are additive</li>
</ul>
</li>
<li>small F value/big p value - DENSITY:SEASON - no interaction</li>
</ul>
</li>
</ul>
<p>Generate a summary table:</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">limp.mod</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EGGS ~ DENSITY * SEASON, data = limp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.65468 -0.25021 -0.03318  0.28335  0.57532 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           2.664166   0.234118  11.380 3.45e-10 ***
## DENSITY              -0.033650   0.008259  -4.074 0.000591 ***
## SEASONsummer         -0.812282   0.331092  -2.453 0.023450 *  
## DENSITY:SEASONsummer  0.003114   0.011680   0.267 0.792533    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4079 on 20 degrees of freedom
## Multiple R-squared:  0.7135, Adjusted R-squared:  0.6705 
## F-statistic:  16.6 on 3 and 20 DF,  p-value: 1.186e-05</code></pre>
<ul>
<li>Upper portion of the table:
<ul>
<li>R lists things alphanumerically (spring would be listed before summer)</li>
<li>SEASONsummer is the difference between the spring and summer y intercepts</li>
<li>My rough calculations estimated this to be -0.756, which is very close to their -0.81</li>
<li>DENSITY:SEASONsummer is the difference between slopes for spring and summer
<ul>
<li>In other words, it is the change in the rate of density dependence that arises from shifting from spring to summer</li>
</ul>
</li>
<li>In the summmer, the density dependence was only 0.003 units (egg prod/density) lower than in spring which was found not to be statistically significant</li>
<li>Summer reduces egg production compared with spring, on average, by 0.812 eggs - significant</li>
</ul>
</li>
<li>Bottom of coefficients table:
<ul>
<li>Adjusted R-squared (0.6705) - means that the model we have fitted explains 67% of the variation in egg production</li>
<li>Low p value - the model has a signficant fit to the data p &lt; 0.001</li>
<li>Large F statistic</li>
</ul>
</li>
</ul>
</div>
<div id="putting-the-lines-onto-the-figure" class="section level3" number="6.2.2">
<h3>
<span class="header-section-number">6.2.2</span> Putting the lines onto the figure<a class="anchor" aria-label="anchor" href="#putting-the-lines-onto-the-figure"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>We need to predict some y values using a sensible range of x values
<ul>
<li>We can use the model eggs(spring) = 2.66 - 0.033 x DENSITY to accomplish this</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">limp.mod</span><span class="op">)</span></code></pre></div>
<pre><code>##          (Intercept)              DENSITY         SEASONsummer 
##          2.664166462         -0.033649651         -0.812282493 
## DENSITY:SEASONsummer 
##          0.003113571</code></pre>
<p>Build a factorial representation of variables and output a grid of numbers:</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>FIRST <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"A"</span>,<span class="st">"B"</span><span class="op">)</span>, SECOND <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>  </code></pre></div>
<pre><code>##   FIRST SECOND
## 1     A      1
## 2     B      1
## 3     A      2
## 4     B      2</code></pre>
<p>Predict y values at all provided x values:</p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">limp.mod</span><span class="op">)</span> </code></pre></div>
<pre><code>##         1         2         3         4         5         6         7         8 
## 2.3949692 2.3949692 2.3949692 1.6075953 1.6075953 1.6075953 2.1594217 2.1594217 
##         9        10        11        12        13        14        15        16 
## 2.1594217 1.3938428 1.3938428 1.3938428 1.6546769 1.6546769 1.6546769 0.9358016 
##        17        18        19        20        21        22        23        24 
## 0.9358016 0.9358016 1.1499321 1.1499321 1.1499321 0.4777604 0.4777604 0.4777604</code></pre>
<ul>
<li>24 values returned because, 2 seasons x 4 density treatments x 3 replicates = 24</li>
</ul>
<p>To generate a new set of x values we could use:</p>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">new.x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>DENSITY <span class="op">=</span>              
                       <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span><span class="fl">8</span>, to<span class="op">=</span><span class="fl">45</span>, <span class="co">#the new x values will be between 8 and 45 </span>
                           length.out <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>, <span class="co">#generates 10 new x values for each parameter </span>
                     SEASON <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">limp</span><span class="op">$</span><span class="va">SEASON</span><span class="op">)</span><span class="op">)</span> <span class="co">#sets the parameter as season. </span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">new.x</span><span class="op">)</span></code></pre></div>
<pre><code>##    DENSITY SEASON
## 1  8.00000 spring
## 2 12.11111 spring
## 3 16.22222 spring
## 4 20.33333 spring
## 5 24.44444 spring
## 6 28.55556 spring</code></pre>
<p>We can now embed these ‘new.x’ x values into the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function:</p>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">new.y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">limp.mod</span>, 
                 newdata <span class="op">=</span> <span class="va">new.x</span>, <span class="co">#instructs R to use the new x values </span>
                 interval <span class="op">=</span> <span class="st">'confidence'</span><span class="op">)</span> <span class="co">#for confidence interval around each y value (fit) </span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">new.y</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 2.394969 2.019285 2.770654
## 2 2.256632 1.931230 2.582034
## 3 2.118294 1.834274 2.402315
## 4 1.979957 1.724062 2.235852
## 5 1.841619 1.595998 2.087241
## 6 1.703282 1.447918 1.958646</code></pre>
<p>Now for some housekeeping:</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">addThese</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">new.x</span>, <span class="va">new.y</span><span class="op">)</span> <span class="co">#combines the two dfs into a single one </span>
<span class="va">addThese</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span><span class="va">addThese</span>, EGGS <span class="op">=</span> <span class="va">fit</span><span class="op">)</span> <span class="co">#changes the column name "fit" to EGGS </span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">addThese</span><span class="op">)</span></code></pre></div>
<pre><code>##    DENSITY SEASON     EGGS      lwr      upr
## 1  8.00000 spring 2.394969 2.019285 2.770654
## 2 12.11111 spring 2.256632 1.931230 2.582034
## 3 16.22222 spring 2.118294 1.834274 2.402315
## 4 20.33333 spring 1.979957 1.724062 2.235852
## 5 24.44444 spring 1.841619 1.595998 2.087241
## 6 28.55556 spring 1.703282 1.447918 1.958646</code></pre>
<p>Plot the data:</p>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">limp</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">DENSITY</span>, y <span class="op">=</span> <span class="va">EGGS</span>, colour <span class="op">=</span> <span class="va">SEASON</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">+</span> <span class="co">#specifies the size of the point</span>
  
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span> <span class="co">#adds the regression line and the CI around the fitted line;</span>
    <span class="co">#assumes that x and y are the same as already specified in ggplot</span>
    data <span class="op">=</span> <span class="va">addThese</span>, 
    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">lwr</span>, ymax <span class="op">=</span> <span class="va">upr</span>, <span class="co">#confidence interval </span>
        fill <span class="op">=</span> <span class="va">SEASON</span><span class="op">)</span>, <span class="co">#different fill depending on the SEASON variable </span>
    stat <span class="op">=</span> <span class="st">'identity'</span><span class="op">)</span> <span class="op">+</span> <span class="co">#tells geom_smooth to use what is in the dataframe and not calculate anything else</span>
  
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>spring<span class="op">=</span><span class="st">"green"</span>, summer <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co">#color for the regression line</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>spring<span class="op">=</span><span class="st">"green"</span>, summer <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co">#color for the confidence interval area </span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="_main_files/figure-html/final-limp-plot-1.png" width="672"></div>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="introduction-to-statistics-in-r.html"><span class="header-section-number">5</span> Introduction to Statistics in R</a></div>
<div class="next"><a href="getting-started-with-generalized-linear-models.html"><span class="header-section-number">7</span> Getting Started with Generalized Linear Models</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#advancing-statistics-in-r"><span class="header-section-number">6</span> Advancing Statistics in R</a></li>
<li>
<a class="nav-link" href="#the-two-way-anova"><span class="header-section-number">6.1</span> The two-way ANOVA</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#cow-growth-data"><span class="header-section-number">6.1.1</span> Cow Growth data</a></li></ul>
</li>
<li>
<a class="nav-link" href="#analysis-of-covariance-ancova"><span class="header-section-number">6.2</span> Analysis of Covariance (ANCOVA)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#constructing-the-ancova"><span class="header-section-number">6.2.1</span> Constructing the ANCOVA</a></li>
<li><a class="nav-link" href="#putting-the-lines-onto-the-figure"><span class="header-section-number">6.2.2</span> Putting the lines onto the figure</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/rstudio/bookdown-demo/blob/master/06_adv-stats.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/rstudio/bookdown-demo/edit/master/06_adv-stats.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>A Guide to Getting Started with R</strong>" was written by Pete Apicella. It was last built on 2022-07-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
